package modelos;
// Generated 26-jul-2022 20:25:01 by Hibernate Tools 3.6.0



/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private Integer id;
     private Region region;
     private String nombre;
     private Float area;
     private Integer poblacion;
     private boolean capitalPais;
     private boolean capitalRegion;
     private boolean areaMetropolitana;

    public Ciudad() {
    }

	
    public Ciudad(Region region, String nombre, boolean capitalPais, boolean capitalRegion, boolean areaMetropolitana) {
        this.region = region;
        this.nombre = nombre;
        this.capitalPais = capitalPais;
        this.capitalRegion = capitalRegion;
        this.areaMetropolitana = areaMetropolitana;
    }
    public Ciudad(Region region, String nombre, Float area, Integer poblacion, boolean capitalPais, boolean capitalRegion, boolean areaMetropolitana) {
       this.region = region;
       this.nombre = nombre;
       this.area = area;
       this.poblacion = poblacion;
       this.capitalPais = capitalPais;
       this.capitalRegion = capitalRegion;
       this.areaMetropolitana = areaMetropolitana;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Float getArea() {
        return this.area;
    }
    
    public void setArea(Float area) {
        this.area = area;
    }
    public Integer getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(Integer poblacion) {
        this.poblacion = poblacion;
    }
    public boolean isCapitalPais() {
        return this.capitalPais;
    }
    
    public void setCapitalPais(boolean capitalPais) {
        this.capitalPais = capitalPais;
    }
    public boolean isCapitalRegion() {
        return this.capitalRegion;
    }
    
    public void setCapitalRegion(boolean capitalRegion) {
        this.capitalRegion = capitalRegion;
    }
    public boolean isAreaMetropolitana() {
        return this.areaMetropolitana;
    }
    
    public void setAreaMetropolitana(boolean areaMetropolitana) {
        this.areaMetropolitana = areaMetropolitana;
    }




}


