package modelos;
// Generated 26-jul-2022 20:25:01 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer id;
     private Continente continente;
     private Tiporegion tiporegion;
     private String nombre;
     private String moneda;
     private Set regions = new HashSet(0);

    public Pais() {
    }

	
    public Pais(Continente continente, Tiporegion tiporegion, String nombre) {
        this.continente = continente;
        this.tiporegion = tiporegion;
        this.nombre = nombre;
    }
    public Pais(Continente continente, Tiporegion tiporegion, String nombre, String moneda, Set regions) {
       this.continente = continente;
       this.tiporegion = tiporegion;
       this.nombre = nombre;
       this.moneda = moneda;
       this.regions = regions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Continente getContinente() {
        return this.continente;
    }
    
    public void setContinente(Continente continente) {
        this.continente = continente;
    }
    public Tiporegion getTiporegion() {
        return this.tiporegion;
    }
    
    public void setTiporegion(Tiporegion tiporegion) {
        this.tiporegion = tiporegion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public Set getRegions() {
        return this.regions;
    }
    
    public void setRegions(Set regions) {
        this.regions = regions;
    }




}


