package modelos;
// Generated 26-jul-2022 20:25:01 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tiporegion generated by hbm2java
 */
public class Tiporegion  implements java.io.Serializable {


     private Integer id;
     private String tipoRegion;
     private Set paises = new HashSet(0);

    public Tiporegion() {
    }

	
    public Tiporegion(String tipoRegion) {
        this.tipoRegion = tipoRegion;
    }
    public Tiporegion(String tipoRegion, Set paises) {
       this.tipoRegion = tipoRegion;
       this.paises = paises;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTipoRegion() {
        return this.tipoRegion;
    }
    
    public void setTipoRegion(String tipoRegion) {
        this.tipoRegion = tipoRegion;
    }
    public Set getPaises() {
        return this.paises;
    }
    
    public void setPaises(Set paises) {
        this.paises = paises;
    }




}


